spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task_management_system_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.yaml
    drop-first: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        ddl-auto: none
        show-sql: true
token:
  signing:
    key: 193b712dbb57d09413c783088ef70b37961170114c476a3646017a11cb044a25

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: TRACE